"groups":
- "name": "vault"
  "rules":
  - "alert": "VaultSealed"
    "annotations":
      "dashboard_url": "https://grafana.com/d/vault-overview-skj2/vault-overview?var-instance={{ $labels.instance }}"
      "description": "Vault instance {{ $labels.instance }} is sealed."
      "summary": "Vault is sealed."
    "expr": |
      vault_core_unsealed{
        job=~".*vault.*"
      } == 0
    "for": "0m"
    "labels":
      "severity": "critical"
  - "alert": "VaultDown"
    "annotations":
      "dashboard_url": "https://grafana.com/d/vault-overview-skj2/vault-overview?var-instance={{ $labels.instance }}"
      "description": "Vault instance {{ $labels.instance }} is down."
      "summary": "Vault is down."
    "expr": |
      up{
        job=~".*vault.*"
      } == 0
    "for": "5m"
    "labels":
      "severity": "critical"
  - "alert": "VaultTooManyPendingTokens"
    "annotations":
      "dashboard_url": "https://grafana.com/d/vault-overview-skj2/vault-overview?var-instance={{ $labels.instance }}"
      "description": "More than 0 tokens created but not yet stored on instance {{ $labels.instance }} the past 5m."
      "summary": "Vault has too many pending tokens."
    "expr": |
      avg(
        vault_token_create_count{
          job=~".*vault.*"
        }
        -
        vault_token_store_count{
          job=~".*vault.*"
        }
      ) by (job, instance)
      > 0
    "for": "5m"
    "labels":
      "severity": "warning"
  - "alert": "VaultTooManyInfinityTokens"
    "annotations":
      "dashboard_url": "https://grafana.com/d/vault-overview-skj2/vault-overview?var-instance={{ $labels.instance }}"
      "description": "More than 3 non-expiring tokens on instance {{ $labels.instance }} for the past 5m."
      "summary": "Vault has too many non-expiring tokens."
    "expr": |
      vault_token_count_by_ttl{
        job=~".*vault.*",
        creation_ttl="+Inf"
      }
      > 3
    "for": "5m"
    "labels":
      "severity": "warning"
  - "alert": "VaultClusterHealth"
    "annotations":
      "dashboard_url": "https://grafana.com/d/vault-overview-skj2/vault-overview?var-exported_cluster={{ $labels.cluster }}"
      "description": "Vault cluster is not healthy: only {{ $value | humanizePercentage }} of nodes are unsealed."
      "summary": "Vault cluster is not healthy."
    "expr": |
      sum(
        vault_core_unsealed{
          job=~".*vault.*"
        }
      ) by (cluster)
      /
      count(
        vault_core_unsealed{
          job=~".*vault.*"
        }
      ) by (cluster)
      <= 0.5
    "for": "5m"
    "labels":
      "severity": "critical"
  - "alert": "VaultAutopilotUnhealthy"
    "annotations":
      "dashboard_url": "https://grafana.com/d/vault-overview-skj2/vault-overview?var-instance={{ $labels.instance }}"
      "description": "Vault Autopilot is unhealthy on instance {{ $labels.instance }} for the past 5m."
      "summary": "Vault Autopilot is unhealthy."
    "expr": |
      min(
        vault_autopilot_healthy{
          job=~".*vault.*"
        }
      ) by (job, instance)
      == 0
    "for": "5m"
    "labels":
      "severity": "critical"
  - "alert": "VaultAutopilotNodeUnhealthy"
    "annotations":
      "dashboard_url": "https://grafana.com/d/vault-overview-skj2/vault-overview"
      "description": "Vault Autopilot node {{ $labels.node_id }} is unhealthy for the past 5m."
      "summary": "Vault Autopilot node is unhealthy."
    "expr": |
      vault_autopilot_node_healthy{
        job=~".*vault.*"
      } == 0
    "for": "5m"
    "labels":
      "severity": "warning"
  - "alert": "VaultNoActiveNode"
    "annotations":
      "dashboard_url": "https://grafana.com/d/vault-overview-skj2/vault-overview?var-exported_cluster={{ $labels.cluster }}"
      "description": "Vault cluster {{ $labels.cluster }} has no active node for the past 5m."
      "summary": "Vault has no active node."
    "expr": |
      sum(
        vault_core_active{
          job=~".*vault.*"
        }
      ) by (cluster)
      < 1
    "for": "5m"
    "labels":
      "severity": "critical"
  - "alert": "VaultHighResponseErrorRate"
    "annotations":
      "dashboard_url": "https://grafana.com/d/vault-overview-skj2/vault-overview?var-instance={{ $labels.instance }}"
      "description": "More than 5% Vault responses are errors on instance {{ $labels.instance }} the past 5m."
      "summary": "Vault has a high response error rate."
    "expr": |
      (
        sum(
          rate(
            vault_core_response_status_code{
              job=~".*vault.*",
              type=~"4xx|5xx"
            }[5m]
          )
        ) by (job, instance)
        /
        sum(
          rate(
            vault_core_response_status_code{
              job=~".*vault.*"
            }[5m]
          )
        ) by (job, instance)
        * 100
      ) > 5
      and
      sum(
        rate(
          vault_core_response_status_code{
            job=~".*vault.*",
            type=~"4xx|5xx"
          }[5m]
        )
      ) by (job, instance)
      > 1
    "for": "1m"
    "labels":
      "severity": "warning"
  - "alert": "VaultRaftFSMPendingHigh"
    "annotations":
      "dashboard_url": "https://grafana.com/d/vault-overview-skj2/vault-overview"
      "description": "Vault Raft peer {{ $labels.peer_id }} has more than 100 pending FSM operations for the past 5m."
      "summary": "Vault Raft FSM pending operations are high."
    "expr": |
      vault_raft_storage_stats_fsm_pending{
        job=~".*vault.*"
      }
      > 100
    "for": "5m"
    "labels":
      "severity": "warning"
  - "alert": "VaultAuditFailures"
    "annotations":
      "dashboard_url": "https://grafana.com/d/vault-overview-skj2/vault-overview?var-instance={{ $labels.instance }}"
      "description": "Vault audit log failures are occurring on instance {{ $labels.instance }} for the past 5m."
      "summary": "Vault audit log failures detected."
    "expr": |
      sum(
        (
          rate(
            vault_audit_log_request_failure{
              job=~".*vault.*"
            }[5m]
          )
        )
        or
        (
          rate(
            vault_audit_log_response_failure{
              job=~".*vault.*"
            }[5m]
          )
        )
      ) by (job, instance)
      > 0
    "for": "5m"
    "labels":
      "severity": "warning"
