"groups":
- "name": "vault"
  "rules":
  - "alert": "VaultSealed"
    "annotations":
      "dashboard_url": "https://grafana.com/d/vault-overview-skj2/vault-overview?var-instance={{ $labels.instance }}"
      "description": "Vault instance {{ $labels.instance }} is sealed."
      "summary": "Vault is sealed."
    "expr": |
      vault_core_unsealed{
        job=~".*vault.*"
      } == 0
    "for": "0m"
    "labels":
      "severity": "critical"
  - "alert": "VaultTooManyInfinityTokens"
    "annotations":
      "dashboard_url": "https://grafana.com/d/vault-overview-skj2/vault-overview?var-instance={{ $labels.instance }}"
      "description": "More than 3 non-expiring tokens on instance {{ $labels.instance }} for the past 5m."
      "summary": "Vault has too many non-expiring tokens."
    "expr": |
      vault_token_count_by_ttl{
        job=~".*vault.*",
        creation_ttl="+Inf"
      }
      > 3
    "for": "5m"
    "labels":
      "severity": "warning"
  - "alert": "VaultAutopilotUnhealthy"
    "annotations":
      "dashboard_url": "https://grafana.com/d/vault-overview-skj2/vault-overview?var-instance={{ $labels.instance }}"
      "description": "Vault Autopilot is unhealthy on instance {{ $labels.instance }} for the past 5m."
      "summary": "Vault Autopilot is unhealthy."
    "expr": |
      min(
        vault_autopilot_healthy{
          job=~".*vault.*"
        }
      ) by (job, instance)
      == 0
    "for": "5m"
    "labels":
      "severity": "critical"
  - "alert": "VaultNoActiveNode"
    "annotations":
      "dashboard_url": "https://grafana.com/d/vault-overview-skj2/vault-overview?var-exported_cluster={{ $labels.cluster }}"
      "description": "Vault cluster {{ $labels.cluster }} has no active node for the past 5m."
      "summary": "Vault has no active node."
    "expr": |
      sum(
        vault_core_active{
          job=~".*vault.*"
        }
      ) by (cluster)
      < 1
    "for": "5m"
    "labels":
      "severity": "critical"
  - "alert": "VaultLowResponseSuccessRate"
    "annotations":
      "dashboard_url": "https://grafana.com/d/vault-overview-skj2/vault-overview?var-instance={{ $labels.instance }}"
      "description": "Less than 95% of Vault responses are non-5xx on instance {{ $labels.instance }} the past 5m."
      "summary": "Vault has a low response success rate."
    "expr": |
      (
        1 -
        (
          sum(
            rate(
              vault_core_response_status_code{
                job=~".*vault.*",
                type="5xx"
              }[5m]
            )
          ) by (job, instance)
          /
          sum(
            rate(
              vault_core_response_status_code{
                job=~".*vault.*"
              }[5m]
            )
          ) by (job, instance)
        )
      )
        * 100
      < 95
      and
      sum(
        rate(
          vault_core_response_status_code{
            job=~".*vault.*",
            type="5xx"
          }[5m]
        )
      ) by (job, instance)
      > 1
    "for": "1m"
    "labels":
      "severity": "warning"
  - "alert": "VaultRaftFSMPendingHigh"
    "annotations":
      "dashboard_url": "https://grafana.com/d/vault-overview-skj2/vault-overview"
      "description": "Vault Raft peer {{ $labels.peer_id }} has more than 100 pending FSM operations for the past 5m."
      "summary": "Vault Raft FSM pending operations are high."
    "expr": |
      vault_raft_storage_stats_fsm_pending{
        job=~".*vault.*"
      }
      > 100
    "for": "5m"
    "labels":
      "severity": "warning"
  - "alert": "VaultAuditFailures"
    "annotations":
      "dashboard_url": "https://grafana.com/d/vault-overview-skj2/vault-overview?var-instance={{ $labels.instance }}"
      "description": "Vault audit log failures are occurring on instance {{ $labels.instance }} for the past 5m."
      "summary": "Vault audit log failures detected."
    "expr": |
      sum(
        (
          rate(
            vault_audit_log_request_failure{
              job=~".*vault.*"
            }[5m]
          )
        )
        or
        (
          rate(
            vault_audit_log_response_failure{
              job=~".*vault.*"
            }[5m]
          )
        )
      ) by (job, instance)
      > 0
    "for": "5m"
    "labels":
      "severity": "warning"
